---
image: quay.io/podman/stable

stages:
  #  - lint
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

.defaults: &defaults
  image: python:3
  tags:
    - shared

#lint:hooks:
#  <<: *defaults
#  stage: lint
#  allow_failure: true
#  before_script:
#    - pip install pre-commit
#  script:
#    - pre-commit run --all-files --verbose --show-diff-on-failure

#test:py36: &test
#  <<: *defaults
#  image: python:3.6
#  stage: test
#  script:
#    - tox -e py36
#
#test:py37:
#  <<: *test
#  image: python:3.7
#  script:
#    - tox -e py37
#
#test:py38:
#  <<: *test
#  image: python:3.8
#  script:
#    - tox -e py38
#
#test:py39:
#  <<: *test
#  image: python:3.9
#  script:
#    - tox -e py39

test:e2e:
  image: python:3.8
  script:
    - make e2e
