# default schema for the plugin
---
type: map
allowempty: false
mapping:
  executable_path:
    required: false
    type: str
  container_name:
    required: false
    type: str
  image:
    required: true
    type: str
  entrypoint:
    required: false
    type: str
  privileged:
    required: false
    type: bool
  remove:
    required: false
    type: bool
  tty:
    required: false
    type: bool
  network_mode:
    required: false
    type: str
    enum: ["bridge", "none", "host"]
  environment:
    required: false
    type: seq
    sequence:
      - type: str
  ports:
    required: false
    type: seq
    sequence:
      - type: str
  volumes:
    required: false
    type: seq
    sequence:
      - type: str
        func: valid_volume_path
  capabilities:
    required: false
    type: map
    mapping:
      add:
        required: false
        type: seq
        sequence:
          - type: str
      drop:
        required: false
        type: seq
        sequence:
          - type: str
  additional_args:
    required: false
    type: seq
    sequence:
      - type: str
  remote:
    required: false
    type: map
    mapping:
      user:
        required: true
        type: str
      identity:
        required: true
        type: str
      uri:
        required: true
        type: str
  credential:
    type: map
    required: false
    mapping:
      username:
        required: true
        type: str
      password:
        required: true
        type: str
      registry:
        required: true
        type: str
  ansible_params:
    required: true
    type: map
    allowempty: false
    mapping:
      ansible_connection:
        type: str
        required: true
        enum: ["podman"]
